import Head from "next/head";
import c from "@/styles/pages/index.module.css";
import Door from "@/components/Door/Door";
import Params from "@/components/Params/Params";

export default function Home() {

  return (
    <>
      <Head>
        <title>Двери</title>
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"  />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={c.container}>
          <Door />
          <Params />
        </div>
      </main>
    </>
  );
}
